name:python cl
 on:[push]
 jobs:
  bulid:
    runs-on:ubuntu-latest
  steps:
   -users:actions/checkout@v3
   -users:actions/setup-python@v4
with:
    python-version:'3.x'
  -runs:python app.py can u explain